# Generated by Django 6.1.1 on 2026-09-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_examresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='learning_plan',
            field=models.TextField(blank=True, default=''),
        ),
    ]
