# Generated by Django 6.1.1 on 2026-09-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_examresult_learning_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=30)),
                ('track', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('subtopic', models.CharField(blank=True, max_length=100)),
                ('difficulty', models.CharField(choices=[('beginner', 'مبتدی'), ('medium', 'متوسط'), ('good', 'خوب'), ('advanced', 'پیشرفته'), ('professional', 'حرفه\u200cای'), ('tizhooshan', 'تیزهوشان')], default='beginner', max_length=20)),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(choices=[('a', 'گزینه الف'), ('b', 'گزینه ب'), ('c', 'گزینه ج'), ('d', 'گزینه د')], max_length=1)),
                ('explanation', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
