# Generated by Django 6.1.1 on 2026-09-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetotp',
            name='code',
            field=models.CharField(max_length=128),
        ),
    ]
